line-length = 120
indent-width = 4

[lint]
# Enable sorting
select = ["I"]

[lint.isort]
known-first-party = [
    "Glacier2",
    "IcePy",
    "Ice",
    "IceBox",
    "IceGrid",
    "IceMX",
    "IceStorm",
]

[format]
# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = true
docstring-code-line-length = 88
