name: "Build Swift Packages"

on:
  workflow_call:
    inputs:
      ice_version:
        required: false
        type: string
      repository_url:
        required: false
        type: string
    secrets:
      ICE_SWIFT_NIGHTLY_TOKEN:
        required: false

jobs:
  build-swift-packages:
    runs-on: macos-15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup C++
        uses: ./.github/actions/setup-cpp

      - name: Setup Cache
        uses: ./.github/actions/setup-cache
        with:
          prefix: build-swift-packages

      - name: Create ice-swift repository
        run: |
          cd packaging/swift
          ./update-ice-swift-nightly.sh "${{ inputs.ice_version }}" "${{ inputs.repository_url }}"

          echo "Testing ice-swift build..."
          swift build --package-path ice-swift-nightly --configuration release
        env:
          ICE_SWIFT_NIGHTLY_TOKEN: ${{ secrets.ICE_SWIFT_NIGHTLY_TOKEN }}
